### ISSUE TITLE
Error: Windows is not supported.

### ISSUE THREAD

**Issue by Reqeique** [londogard/londogard-nlp-toolkit#70]
I am getting error while I am running simple code snippet 
```
SentencePieceTokenizer.fromLanguageSupportOrNull(LanguageSupport.en)?.split(string)
```
error
```
Exception in thread "main" java.lang.UnsupportedOperationException: Windows is not supported.
	at ai.djl.sentencepiece.jni.LibUtils.loadLibrary(LibUtils.java:49)
	at ai.djl.sentencepiece.SpProcessor.<clinit>(SpProcessor.java:26)
	at ai.djl.sentencepiece.SpTokenizer.<init>(SpTokenizer.java:49)
	at ai.djl.sentencepiece.SpTokenizer.<init>(SpTokenizer.java:38)
	at com.londogard.nlp.tokenizer.SentencePieceTokenizer.<init>(SentencePieceTokenizer.kt:10)
	at com.londogard.nlp.tokenizer.SentencePieceTokenizer$Companion.fromLanguageSupportAndSizeOrNull(SentencePieceTokenizer.kt:26)
	at com.londogard.nlp.tokenizer.SentencePieceTokenizer$Companion.fromLanguageSupportOrNull(SentencePieceTokenizer.kt:22)
	at MainKt.main(Main.kt:24)
	at MainKt.main(Main.kt)
```

env 
os = win 11 v 21h2(os build 22000.318)
kotlin_v = 1.5.30
java_v = 15.0.2

**Comment by Lundez** [comment]
Hi, great find!

I've filed a rdar for the library I'm using for the JNI (DJL): https://github.com/deepjavalibrary/djl/issues/1411
I hope they'll solve the issue ASAP. If the response isn't that they'll fix it ASAP I'll go on and use the following JNI-wrapper which already includes Windows-support: https://github.com/levyfan/sentencepiece-jni which already includes Windows support :)

That would mean a new dependency added though (even if replacing a old one), which I hope I don't need to do.

**Comment by Lundez** [comment]
PR for fixing issue: https://github.com/deepjavalibrary/djl/pull/1412

**Comment by Reqeique** [comment]
So it would get fixed on the upcoming release

**Comment by Lundez** [comment]
Yeah, but I could use a preview branch until that release is up.
I'll have a solution by end of weekend I hope!

**Comment by Reqeique** [comment]
thank you for your concern :)

**Comment by Lundez** [comment]
@Reqeique FYI we just got the Windows support merged in DJL after I added a PR with most of the changes.

I'll try to grab a beta release of djl-sentencepiece and release a minor release bump until DJL does a real release. 👍

**Comment by Lundez** [comment]
@Reqeique sorry for the time, couldn't find the pre-release of DJL until now. Windows binary now exists!
